### ISSUE TITLE
Google Pay does not work 

### ISSUE THREAD

**Issue by fspathara** [PotatoDevices/device_xiaomi_davinci#2]
When I try to enroll a new card with Google Pay, I get the following error. Please note that I haven't installed Magisk 
![Screenshot_20220423-143804_Google Play services](https://user-images.githubusercontent.com/66828845/164892933-c67e8a6c-4a98-4cc6-87ce-071482b9a733.png)

**Comment by adi8900** [comment]
expected, digest fails when i am using fake props to pass safetynet by default and phone boots with everything broken, modem doesnt just mount... flash magisk and enable magisk hide, there isnt another way sadly
